# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sRqxVQcm0qNlRafXukp8eTy2YFPsq9ks
"""

import streamlit as st
import pandas as pd
import plotly.graph_objects as go

# ---------------------------------------------------------
# 1. CONFIGURAÇÃO INICIAL DA PÁGINA
# ---------------------------------------------------------
st.set_page_config(layout="wide", page_title="Painel de Obras 360", page_icon="🏗️")

# Estilo CSS Personalizado para remover margens excessivas
st.markdown("""
<style>
    .block-container {padding-top: 1.5rem; padding-bottom: 1rem;}
    [data-testid="stMetricValue"] {font-size: 1.5rem;}
</style>
""", unsafe_allow_html=True)

# ---------------------------------------------------------
# 2. CARREGAMENTO DE DADOS
# ---------------------------------------------------------
@st.cache_data
def load_data():
    return pd.read_excel("dados_obras_v3.xlsx")

try:
    df_raw = load_data()
except FileNotFoundError:
    st.error("⚠️ Arquivo 'dados_obras_v3.xlsx' não encontrado. Rode o script gerar_dados.py primeiro!")
    st.stop()

# ---------------------------------------------------------
# 3. SIDEBAR (FILTROS)
# ---------------------------------------------------------
st.sidebar.image("https://cdn-icons-png.flaticon.com/512/25/25613.png", width=50) # Ícone Genérico
st.sidebar.title("Gestão de Obras")
st.sidebar.markdown("---")

projetos = df_raw['Projeto'].unique()
projeto_sel = st.sidebar.selectbox("📂 Selecione o Projeto:", projetos)

# Filtrar o projeto selecionado
dados = df_raw[df_raw['Projeto'] == projeto_sel].iloc[0]

st.sidebar.markdown("---")
st.sidebar.info("Dashboard v3.0\nVisualização Executiva")

# ---------------------------------------------------------
# 4. CÁLCULOS PRINCIPAIS
# ---------------------------------------------------------
# Custo Total Real = Materiais + Despesas + Mão de Obra (Valor) + Impostos
custo_total = dados['Mat_Real'] + dados['Desp_Real'] + dados['HH_Real_Vlr'] + dados['Impostos']

# Lucro Líquido
lucro_liquido = dados['Vendido'] - custo_total

# Margem Real (%)
margem_real_pct = (lucro_liquido / dados['Vendido']) * 100 if dados['Vendido'] > 0 else 0

# ---------------------------------------------------------
# 5. HEADER (CABEÇALHO)
# ---------------------------------------------------------
col_tit, col_status = st.columns([3, 1])

with col_tit:
    st.title(f"{dados['Projeto']} | {dados['Cliente']}")
    st.caption(f"📍 Local: {dados['Cidade']} | 📄 Contrato: R$ {dados['Vendido']:,.2f}")

with col_status:
    # Badge Dinâmico de Status
    cor_map = {"Finalizado": "green", "Em andamento": "blue", "Não iniciado": "gray", "Apresentado": "orange"}
    cor = cor_map.get(dados['Status'], "gray")
    st.markdown(f"### :{cor}[{dados['Status']}]")

st.divider()

# ---------------------------------------------------------
# 6. LINHA 1: INDICADORES MACRO (KPIs)
# ---------------------------------------------------------
kpi1, kpi2, kpi3, kpi4 = st.columns(4)

kpi1.metric("💰 Valor Vendido", f"R$ {dados['Vendido']:,.2f}")
kpi2.metric("📝 Faturado", f"R$ {dados['Faturado']:,.2f}")
kpi3.metric("📉 Custo Total (+Imp)", f"R$ {custo_total:,.2f}", help="Soma de Mat + Desp + HH + Impostos")

# Margem com delta colorido
delta_margem = margem_real_pct - 25.0
kpi4.metric(
    "📈 Margem Real",
    f"{margem_real_pct:.1f}%",
    delta=f"{delta_margem:.1f}% (Meta 25%)",
    delta_color="normal" # Vermelho se negativo, Verde se positivo
)

st.write("") # Espaço

# ---------------------------------------------------------
# 7. LINHA 2: EFICIÊNCIA OPERACIONAL (Gráficos Visuais)
# ---------------------------------------------------------
st.subheader("⚙️ Eficiência Operacional")

col_fisico, col_hh, col_msg = st.columns([2, 2, 2])

# A) Gráfico de Progresso Físico
with col_fisico:
    st.markdown("**Conclusão Física da Obra**")
    progresso_fisico = dados['Conclusao_%']
    st.progress(progresso_fisico / 100)
    st.caption(f"{progresso_fisico}% dos serviços executados.")

# B) Gráfico de Consumo de Horas (HH)
with col_hh:
    hh_total = dados['HH_Orc_Qtd']
    hh_consumido = dados['HH_Real_Qtd']

    if hh_total > 0:
        perc_hh = (hh_consumido / hh_total) * 100
    else:
        perc_hh = 0

    st.markdown(f"**Consumo Banco de Horas** ({int(hh_consumido)} / {int(hh_total)} h)")

    # Lógica da Barra de Horas: Fica vermelha se gastou mais horas do que o progresso da obra
    barra_valor = min(perc_hh / 100, 1.0)

    # Se consumiu 80% das horas mas obra está em 50%, é ruim.
    if perc_hh > (progresso_fisico + 10):
        # Gambiarra visual: Streamlit não deixa mudar cor nativa fácil,
        # mas o contexto ajuda. Usamos aviso abaixo.
        pass

    st.progress(barra_valor)
    st.caption(f"{perc_hh:.1f}% das horas orçadas foram utilizadas.")

# C) Mensagem de Insight Automática
with col_msg:
    st.write("") # Alinhar verticalmente
    if perc_hh > (progresso_fisico + 15):
        st.error(f"⚠️ **Atenção Crítica:** O consumo de horas ({perc_hh:.0f}%) está muito acima do andamento da obra ({progresso_fisico}%)! Risco de prejuízo na Mão de Obra.")
    elif perc_hh > progresso_fisico:
        st.warning(f"⚠️ **Cuidado:** Consumo de horas levemente descolado da produção.")
    elif progresso_fisico == 0:
        st.info("ℹ️ Obra não iniciada.")
    else:
        st.success(f"✅ **Eficiente:** Equipe está performando bem. Obra avançada com economia de horas.")

st.divider()

# ---------------------------------------------------------
# 8. LINHA 3: DETALHAMENTO FINANCEIRO
# ---------------------------------------------------------
st.subheader("📊 Raio-X Financeiro")

tab1, tab2 = st.tabs(["Cascata de Lucro", "Comparativo Orçado x Real"])

# --- TAB 1: GRÁFICO CASCATA (Waterfall) ---
with tab1:
    fig_water = go.Figure(go.Waterfall(
        name = "20", orientation = "v",
        measure = ["relative", "relative", "relative", "relative", "relative", "total"],
        x = ["Vendido", "Impostos", "Materiais", "Despesas", "Mão de Obra", "Lucro Líquido"],
        textposition = "outside",
        text = [f"{dados['Vendido']/1000:.0f}k", f"-{dados['Impostos']/1000:.1f}k",
                f"-{dados['Mat_Real']/1000:.1f}k", f"-{dados['Desp_Real']/1000:.1f}k",
                f"-{dados['HH_Real_Vlr']/1000:.1f}k", f"{lucro_liquido/1000:.1f}k"],
        y = [dados['Vendido'], -dados['Impostos'], -dados['Mat_Real'],
             -dados['Desp_Real'], -dados['HH_Real_Vlr'], lucro_liquido],
        connector = {"line":{"color":"rgb(63, 63, 63)"}},
        decreasing = {"marker":{"color":"#ef4444"}}, # Vermelho para saídas
        increasing = {"marker":{"color":"#10b981"}}, # Verde para entradas
        totals = {"marker":{"color":"#3b82f6"}}       # Azul para o resultado
    ))

    fig_water.update_layout(title="Composição do Resultado (R$)", height=400)
    st.plotly_chart(fig_water, use_container_width=True)

# --- TAB 2: GRÁFICOS COMPARATIVOS ---
with tab2:
    col1, col2, col3 = st.columns(3)

    def criar_grafico_comparativo(titulo, orcado, real):
        cor_barra = '#ef4444' if real > orcado else '#3b82f6' # Vermelho se estourar
        fig = go.Figure()
        fig.add_trace(go.Bar(
            x=['Orçado', 'Realizado'], y=[orcado, real],
            text=[f"R$ {orcado:,.0f}", f"R$ {real:,.0f}"],
            textposition='auto',
            marker_color=['#9ca3af', cor_barra] # Cinza vs Cor
        ))
        fig.update_layout(title=titulo, height=300, margin=dict(l=20, r=20, t=40, b=20))
        return fig

    with col1:
        st.plotly_chart(criar_grafico_comparativo("Materiais", dados['Mat_Orc'], dados['Mat_Real']), use_container_width=True)
    with col2:
        st.plotly_chart(criar_grafico_comparativo("Despesas", dados['Desp_Orc'], dados['Desp_Real']), use_container_width=True)
    with col3:
        st.plotly_chart(criar_grafico_comparativo("Mão de Obra (Valor)", dados['HH_Orc_Vlr'], dados['HH_Real_Vlr']), use_container_width=True)

from google.colab import drive
drive.mount('/content/drive')